name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - app
  - packages/mini_tea
  - packages/mini_tea_flutter
  - packages/mini_tea_test
dev_dependencies:
  melos: ^7.3.0
  flutter_lints: ^6.0.0