name: mini_tools
description: "-"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_timezone: ^2.1.0
  freezed: ^3.0.0-0.0.dev
  intl: ^0.19.0
  macos_ui: ^2.0.8
  syntax_highlight: ^0.4.0
  timezone: ^0.9.4
  window_manager: ^0.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
