name: mini_tools
description: "-"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  convert: ^3.1.1
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.6
  desktop_drop: ^0.4.4
  diff_match_patch: ^0.4.1
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hsvcolor_picker: ^1.5.1
  flutter_popup: ^3.3.0
  flutter_timezone: ^2.1.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  image: ^4.5.3
  intl: ^0.19.0
  json_path: ^0.7.4
  linked_scroll_controller: ^0.2.0
  logging: ^1.3.0
  macos_ui: ^2.0.8
  meta: ^1.15.0
  mini_tea: ^0.1.2
  mini_tea_flutter: ^0.2.0
  package_info_plus: ^8.3.0
  path: ^1.9.0
  pointycastle: ^3.9.1
  provider: ^6.1.2
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  re_editor: ^0.3.1
  re_highlight: ^0.0.3
  responsive_grid: ^2.4.4
  rxdart: ^0.28.0
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  super_clipboard: ^0.8.24
  timezone: ^0.9.4
  uuid: ^4.5.1
  window_manager: ^0.4.0

  blurhash_ffi: ^1.2.7

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mini_tea_test: ^0.2.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
