name: mini_tools
description: "-"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.6
  desktop_drop: ^0.4.4
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hsvcolor_picker: ^1.5.1
  flutter_timezone: ^2.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.4
  macos_ui: ^2.0.8
  meta: ^1.15.0
  path: ^1.9.0
  pointycastle: ^3.9.1
  re_editor: ^0.3.1
  re_highlight: ^0.0.3
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  syntax_highlight: ^0.4.0
  timezone: ^0.9.4
  window_manager: ^0.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
